-- Generated Nodes for Journey Map
-- This file contains all 114 surahs mapped to their thematic islands
-- Generated based on Islamic scholarly analysis of Quranic themes

INSERT INTO nodes (island_id, name, name_ar, type, content_refs, completion_criteria, description, xp_reward, seed_reward, order_index, estimated_minutes) VALUES
-- Island 1: Fondasi Iman (Foundations of Faith)
(1, 'Al-Fatihah', 'الفاتحة', 'surah', '{"surah_id": 1}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Opening - Foundation of all prayer and faith', 20, 5, 1, 2),
(1, 'Al-Ikhlas', 'الإخلاص', 'surah', '{"surah_id": 112}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Pure monotheism and the essence of tawhid', 15, 4, 2, 1),
(1, 'Al-Kafirun', 'الكافرون', 'surah', '{"surah_id": 109}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Declaration of faith and rejection of shirk', 15, 4, 3, 1),
(1, 'Al-Baqarah', 'البقرة', 'surah', '{"surah_id": 2}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Comprehensive guidance covering all aspects of faith', 500, 100, 4, 120),
(1, 'Ali Imran', 'آل عمران', 'surah', '{"surah_id": 3}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Family of Imran - Faith, trials, and steadfastness', 350, 70, 5, 80),

-- Island 2: Kisah Para Nabi (Prophetic Narratives)
(2, 'Yusuf', 'يوسف', 'surah', '{"surah_id": 12}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The beautiful story of Prophet Yusuf', 200, 40, 6, 45),
(2, 'Maryam', 'مريم', 'surah', '{"surah_id": 19}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Stories of Maryam, Isa, Ibrahim, and other prophets', 150, 30, 7, 35),
(2, 'Al-Anbiya', 'الأنبياء', 'surah', '{"surah_id": 21}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Stories of multiple prophets and their missions', 180, 36, 8, 40),
(2, 'Al-Qasas', 'القصص', 'surah', '{"surah_id": 28}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The story of Musa in detail', 170, 34, 9, 40),
(2, 'Hud', 'هود', 'surah', '{"surah_id": 11}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Stories of Hud, Salih, Lut, and Shuayb', 200, 40, 10, 45),
(2, 'Ibrahim', 'إبراهيم', 'surah', '{"surah_id": 14}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Prophet Ibrahim and his legacy', 100, 20, 11, 25),
(2, 'Nuh', 'نوح', 'surah', '{"surah_id": 71}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The story of Prophet Nuh', 50, 10, 12, 10),
(2, 'Yunus', 'يونس', 'surah', '{"surah_id": 10}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Prophet Yunus and lessons of patience', 180, 36, 13, 40),
(2, 'Sad', 'ص', 'surah', '{"surah_id": 38}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Stories of Dawud, Sulayman, and Ayyub', 140, 28, 14, 30),
(2, 'As-Saffat', 'الصافات', 'surah', '{"surah_id": 37}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Angels and prophetic narratives', 150, 30, 15, 35),

-- Island 3: Hukum & Syariat (Laws & Governance)
(3, 'An-Nisa', 'النساء', 'surah', '{"surah_id": 4}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Laws regarding women, inheritance, and family', 350, 70, 16, 80),
(3, 'Al-Maidah', 'المائدة', 'surah', '{"surah_id": 5}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Contracts, food laws, and criminal law', 280, 56, 17, 60),
(3, 'Al-Anfal', 'الأنفال', 'surah', '{"surah_id": 8}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Laws of war and distribution of spoils', 140, 28, 18, 30),
(3, 'At-Tawbah', 'التوبة', 'surah', '{"surah_id": 9}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Treaties, warfare, and repentance', 250, 50, 19, 55),
(3, 'An-Nur', 'النور', 'surah', '{"surah_id": 24}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Social laws, modesty, and light of Allah', 130, 26, 20, 30),
(3, 'Al-Ahzab', 'الأحزاب', 'surah', '{"surah_id": 33}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Laws regarding the Prophet and his household', 140, 28, 21, 30),
(3, 'Al-Hujurat', 'الحجرات', 'surah', '{"surah_id": 49}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Social etiquette and brotherhood', 40, 8, 22, 8),
(3, 'Al-Mumtahanah', 'الممتحنة', 'surah', '{"surah_id": 60}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Relations with non-Muslims', 35, 7, 23, 7),

-- Island 4: Hari Akhir (The Afterlife)
(4, 'Al-Waqi''ah', 'الواقعة', 'surah', '{"surah_id": 56}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Event - Three groups on Judgment Day', 80, 16, 24, 15),
(4, 'Ar-Rahman', 'الرحمن', 'surah', '{"surah_id": 55}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Most Merciful - Blessings and Paradise', 75, 15, 25, 15),
(4, 'Al-Mulk', 'الملك', 'surah', '{"surah_id": 67}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Sovereignty - Protection from grave punishment', 50, 10, 26, 10),
(4, 'Al-Qiyamah', 'القيامة', 'surah', '{"surah_id": 75}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Resurrection', 40, 8, 27, 8),
(4, 'Al-Insan', 'الإنسان', 'surah', '{"surah_id": 76}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Man and the rewards of Paradise', 50, 10, 28, 10),
(4, 'An-Naba', 'النبأ', 'surah', '{"surah_id": 78}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Great News of Resurrection', 40, 8, 29, 8),
(4, 'Al-Infitar', 'الانفطار', 'surah', '{"surah_id": 82}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Cleaving - Signs of the Hour', 25, 5, 30, 5),
(4, 'Al-Mutaffifin', 'المطففين', 'surah', '{"surah_id": 83}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Defrauders and their fate', 40, 8, 31, 8),
(4, 'Al-Ghashiyah', 'الغاشية', 'surah', '{"surah_id": 88}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Overwhelming Event', 30, 6, 32, 6),
(4, 'Az-Zalzalah', 'الزلزلة', 'surah', '{"surah_id": 99}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Earthquake of Judgment Day', 15, 3, 33, 3),
(4, 'Al-Qari''ah', 'القارعة', 'surah', '{"surah_id": 101}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Striking Hour', 15, 3, 34, 3),

-- Island 5: Ibadah & Ketaatan (Worship & Devotion)
(5, 'Al-Hajj', 'الحج', 'surah', '{"surah_id": 22}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Pilgrimage and its rituals', 140, 28, 35, 30),
(5, 'Al-Jumu''ah', 'الجمعة', 'surah', '{"surah_id": 62}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Friday prayer and its importance', 25, 5, 36, 5),
(5, 'Al-Muzzammil', 'المزمل', 'surah', '{"surah_id": 73}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Night prayer and devotion', 35, 7, 37, 7),
(5, 'Al-Muddaththir', 'المدثر', 'surah', '{"surah_id": 74}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Cloaked One - Call to worship', 55, 11, 38, 12),
(5, 'Al-A''la', 'الأعلى', 'surah', '{"surah_id": 87}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Most High - Glorification', 25, 5, 39, 5),
(5, 'Al-Fajr', 'الفجر', 'surah', '{"surah_id": 89}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Dawn - Worship and warning', 35, 7, 40, 7),
(5, 'Al-Kawthar', 'الكوثر', 'surah', '{"surah_id": 108}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Abundance - Prayer and sacrifice', 10, 2, 41, 1),
(5, 'Al-Ma''un', 'الماعون', 'surah', '{"surah_id": 107}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Small Kindnesses - True worship', 15, 3, 42, 2),

-- Island 6: Keluarga & Masyarakat (Family & Society)
(6, 'At-Talaq', 'الطلاق', 'surah', '{"surah_id": 65}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Divorce laws and procedures', 30, 6, 43, 6),
(6, 'At-Tahrim', 'التحريم', 'surah', '{"surah_id": 66}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Prohibition - Family matters', 30, 6, 44, 6),
(6, 'Luqman', 'لقمان', 'surah', '{"surah_id": 31}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Wisdom in parenting and family', 60, 12, 45, 12),
(6, 'Al-Isra', 'الإسراء', 'surah', '{"surah_id": 17}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Night Journey - Family and social duties', 180, 36, 46, 40),
(6, 'Ar-Rum', 'الروم', 'surah', '{"surah_id": 30}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Romans - Signs in creation and family', 100, 20, 47, 22),

-- Island 7: Kesabaran & Ujian (Patience & Trials)
(7, 'Al-Ankabut', 'العنكبوت', 'surah', '{"surah_id": 29}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Spider - Tests of faith', 120, 24, 48, 25),
(7, 'Muhammad', 'محمد', 'surah', '{"surah_id": 47}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Struggle and steadfastness', 70, 14, 49, 15),
(7, 'Al-Fath', 'الفتح', 'surah', '{"surah_id": 48}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Victory - Patience rewarded', 55, 11, 50, 12),
(7, 'Al-Hadid', 'الحديد', 'surah', '{"surah_id": 57}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Iron - Strength through trials', 55, 11, 51, 12),
(7, 'Al-Hashr', 'الحشر', 'surah', '{"surah_id": 59}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Gathering - Lessons from exile', 50, 10, 52, 10),
(7, 'As-Saff', 'الصف', 'surah', '{"surah_id": 61}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Ranks - Unity in struggle', 30, 6, 53, 6),
(7, 'Al-Asr', 'العصر', 'surah', '{"surah_id": 103}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Time - Patience and truth', 10, 2, 54, 1),
(7, 'Al-Balad', 'البلد', 'surah', '{"surah_id": 90}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The City - Struggle of life', 30, 6, 55, 6),
(7, 'Ash-Sharh', 'الشرح', 'surah', '{"surah_id": 94}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Relief after hardship', 15, 3, 56, 2),

-- Island 8: Tanda-tanda Alam (Signs in Nature)
(8, 'Al-An''am', 'الأنعام', 'surah', '{"surah_id": 6}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Cattle - Signs in creation', 280, 56, 57, 60),
(8, 'Al-A''raf', 'الأعراف', 'surah', '{"surah_id": 7}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Heights - Creation and history', 350, 70, 58, 80),
(8, 'Ar-Ra''d', 'الرعد', 'surah', '{"surah_id": 13}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Thunder - Signs in nature', 90, 18, 59, 20),
(8, 'An-Nahl', 'النحل', 'surah', '{"surah_id": 16}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Bee - Blessings in creation', 220, 44, 60, 50),
(8, 'Al-Kahf', 'الكهف', 'surah', '{"surah_id": 18}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Cave - Timeless lessons', 180, 36, 61, 40),
(8, 'Ta-Ha', 'طه', 'surah', '{"surah_id": 20}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Ta-Ha - Musa and divine signs', 220, 44, 62, 50),
(8, 'Al-Furqan', 'الفرقان', 'surah', '{"surah_id": 25}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Criterion - Signs of truth', 140, 28, 63, 30),
(8, 'Ash-Shu''ara', 'الشعراء', 'surah', '{"surah_id": 26}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Poets - Signs through prophets', 180, 36, 64, 40),
(8, 'An-Naml', 'النمل', 'surah', '{"surah_id": 27}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Ant - Wisdom in nature', 160, 32, 65, 35),
(8, 'Ya-Sin', 'يس', 'surah', '{"surah_id": 36}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Ya-Sin - Heart of the Quran', 140, 28, 66, 30),
(8, 'Fussilat', 'فصلت', 'surah', '{"surah_id": 41}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Explained in Detail - Signs revealed', 100, 20, 67, 22),
(8, 'Ash-Shura', 'الشورى', 'surah', '{"surah_id": 42}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Consultation - Divine wisdom', 100, 20, 68, 22),
(8, 'Az-Zukhruf', 'الزخرف', 'surah', '{"surah_id": 43}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Gold Adornments - Worldly signs', 110, 22, 69, 24),
(8, 'Ad-Dukhan', 'الدخان', 'surah', '{"surah_id": 44}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Smoke - Cosmic signs', 60, 12, 70, 12),
(8, 'Al-Jathiyah', 'الجاثية', 'surah', '{"surah_id": 45}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Kneeling - Signs of Allah', 70, 14, 71, 15),
(8, 'Al-Ahqaf', 'الأحقاف', 'surah', '{"surah_id": 46}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Sand Dunes - Historical signs', 70, 14, 72, 15),
(8, 'Adh-Dhariyat', 'الذاريات', 'surah', '{"surah_id": 51}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Scattering Winds', 60, 12, 73, 12),
(8, 'At-Tur', 'الطور', 'surah', '{"surah_id": 52}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Mount - Divine oaths', 50, 10, 74, 10),
(8, 'An-Najm', 'النجم', 'surah', '{"surah_id": 53}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Star - Celestial signs', 60, 12, 75, 12),
(8, 'Al-Qamar', 'القمر', 'surah', '{"surah_id": 54}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Moon - Signs and warnings', 55, 11, 76, 11),
(8, 'At-Takwir', 'التكوير', 'surah', '{"surah_id": 81}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Folding Up - Cosmic events', 30, 6, 77, 6),
(8, 'Al-Buruj', 'البروج', 'surah', '{"surah_id": 85}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Constellations', 30, 6, 78, 6),
(8, 'At-Tariq', 'الطارق', 'surah', '{"surah_id": 86}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Night Star', 25, 5, 79, 5),
(8, 'Ash-Shams', 'الشمس', 'surah', '{"surah_id": 91}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Sun - Oaths by creation', 25, 5, 80, 5),
(8, 'Al-Layl', 'الليل', 'surah', '{"surah_id": 92}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Night', 30, 6, 81, 6),
(8, 'Ad-Duha', 'الضحى', 'surah', '{"surah_id": 93}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Morning Hours', 20, 4, 82, 4),
(8, 'At-Tin', 'التين', 'surah', '{"surah_id": 95}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Fig - Sacred places', 15, 3, 83, 3),

-- Island 9: Dialog & Dakwah (Dialogue & Dawah)
(9, 'Al-Hijr', 'الحجر', 'surah', '{"surah_id": 15}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Rocky Tract - Warning to disbelievers', 150, 30, 84, 35),
(9, 'Al-Mu''minun', 'المؤمنون', 'surah', '{"surah_id": 23}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Believers - Characteristics of faith', 180, 36, 85, 40),
(9, 'As-Sajdah', 'السجدة', 'surah', '{"surah_id": 32}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Prostration - Call to worship', 50, 10, 86, 10),
(9, 'Saba', 'سبأ', 'surah', '{"surah_id": 34}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Sheba - Lessons for disbelievers', 100, 20, 87, 22),
(9, 'Fatir', 'فاطر', 'surah', '{"surah_id": 35}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Originator - Invitation to truth', 90, 18, 88, 20),
(9, 'Az-Zumar', 'الزمر', 'surah', '{"surah_id": 39}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Groups - Sincerity in worship', 140, 28, 89, 30),
(9, 'Ghafir', 'غافر', 'surah', '{"surah_id": 40}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Forgiver - Dialogue with Pharaoh', 160, 32, 90, 35),
(9, 'Qaf', 'ق', 'surah', '{"surah_id": 50}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Qaf - Resurrection arguments', 80, 16, 91, 18),
(9, 'Al-Mujadila', 'المجادلة', 'surah', '{"surah_id": 58}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Pleading Woman - Dialogue', 45, 9, 92, 10),
(9, 'Al-Taghabun', 'التغابن', 'surah', '{"surah_id": 64}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Mutual Loss and Gain - Call to faith', 35, 7, 93, 7),
(9, 'Al-Qalam', 'القلم', 'surah', '{"surah_id": 68}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Pen - Response to accusations', 55, 11, 94, 12),
(9, 'Al-Haqqah', 'الحاقة', 'surah', '{"surah_id": 69}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Inevitable - Truth of Quran', 55, 11, 95, 12),
(9, 'Al-Ma''arij', 'المعارج', 'surah', '{"surah_id": 70}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Ways of Ascent - Warning', 50, 10, 96, 10),
(9, 'Al-Jinn', 'الجن', 'surah', '{"surah_id": 72}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Jinn - Universal message', 55, 11, 97, 12),
(9, 'Al-Mursalat', 'المرسلات', 'surah', '{"surah_id": 77}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Those Sent Forth - Warning', 50, 10, 98, 10),
(9, 'Abasa', 'عبس', 'surah', '{"surah_id": 80}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'He Frowned - Dawah priorities', 40, 8, 99, 8),

-- Island 10: Juz Amma (Short Surahs - Beginner Friendly)
(10, 'An-Nazi''at', 'النازعات', 'surah', '{"surah_id": 79}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Those Who Pull Out', 45, 9, 100, 9),
(10, 'Al-Inshiqaq', 'الانشقاق', 'surah', '{"surah_id": 84}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Splitting', 30, 6, 101, 6),
(10, 'Al-Alaq', 'العلق', 'surah', '{"surah_id": 96}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Clot - First revelation', 25, 5, 102, 5),
(10, 'Al-Qadr', 'القدر', 'surah', '{"surah_id": 97}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Night of Power', 15, 3, 103, 2),
(10, 'Al-Bayyinah', 'البينة', 'surah', '{"surah_id": 98}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Clear Evidence', 25, 5, 104, 5),
(10, 'Al-Adiyat', 'العاديات', 'surah', '{"surah_id": 100}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Charging Steeds', 20, 4, 105, 4),
(10, 'At-Takathur', 'التكاثر', 'surah', '{"surah_id": 102}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Competition in Worldly Increase', 15, 3, 106, 3),
(10, 'Al-Humazah', 'الهمزة', 'surah', '{"surah_id": 104}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Slanderer', 15, 3, 107, 3),
(10, 'Al-Fil', 'الفيل', 'surah', '{"surah_id": 105}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Elephant', 15, 3, 108, 2),
(10, 'Quraysh', 'قريش', 'surah', '{"surah_id": 106}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Quraysh', 15, 3, 109, 2),
(10, 'Al-Falaq', 'الفلق', 'surah', '{"surah_id": 113}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Daybreak - Protection', 10, 2, 110, 1),
(10, 'An-Nas', 'الناس', 'surah', '{"surah_id": 114}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Mankind - Seeking refuge', 10, 2, 111, 1),
(10, 'Al-Masad', 'المسد', 'surah', '{"surah_id": 111}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'The Palm Fiber', 10, 2, 112, 1),
(10, 'An-Nasr', 'النصر', 'surah', '{"surah_id": 110}'::jsonb, '{"type": "read_percent", "value": 100}'::jsonb, 'Divine Support', 10, 2, 113, 1);
